# GitHub Actions References:
# https://docs.github.com/en/actions/reference

name: Continuous Integration and Continuous Delivery ⚙🚀

on:
  push:
    branches: [main]

  pull_request:
    types: [opened, synchronize]

jobs:
  test_build:
    name: Test and Build ⚙⚛

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.x, "lts/*"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Use NodeJS ${{ matrix.node }} 📦
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # v2.4.1
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Install Dependencies ✨
        run: yarn --immutable --check-cache

      - name: Run Linter 👨🏻‍💻
        run: yarn type-check && yarn lint

      - name: Run Formatter 💅
        run: yarn format

      - name: Run Test 🛠
        run: yarn test

      - name: Run Build ⚙
        run: yarn build

      - name: Cache dist Directory for Deploy 🚀
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2.1.7
        with:
          path: |
            **/dist
          key: ${{ github.sha }}-${{ runner.os }}-${{ matrix.node }}

  deploy:
    name: Deploy to production ✨🚀

    needs: test_build

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["lts/*"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Restore build cache ♻️
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2.1.7
        with:
          path: |
            **/dist
          key: ${{ github.sha }}-${{ runner.os }}-${{ matrix.node }}

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
